const { test, expect } = require('@playwright/test');
const { ApiClient } = require('../utils/api-client');
const { TestDataFactory } = require('../fixtures/test-data-factory');
const { uiLogin } = require('../utils/ui-login');
const { navigateTo } = require('../utils/navigate');

test.describe('Outbound — Management Flow', () => {
  let api;
  let factory;

  test.beforeEach(async ({ request }) => {
    api = new ApiClient(request);
    factory = new TestDataFactory(api);
  });

  test.afterEach(async () => {
    await factory.cleanup();
  });

  test('full outbound order lifecycle', async ({ page }) => {
    // ----- Step 0: Log in through the real login page -----
    await uiLogin(page);

    // ----- Step 1: Open the outbound plan order page and start creating -----
    await navigateTo(page, '/wms/data-center/outbound/outbound-plan-order');
    await page.click('button:has-text("新增")');
    await page.waitForSelector('.cxd-Modal', { timeout: 15_000 });

    // ----- Step 2: Wizard step 1 — outbound rules -----
    // warehouse is auto-selected from the header warehouse selector; area select
    // has selectFirst so it self-populates.
    await page.locator('.nextButton').click();
    await page.waitForTimeout(1200);

    // ----- Step 3: Wizard step 2 — select the SKU detail from available stock -----
    // The available-stock transfer is pre-loaded with seeded SKU001 (available_qty > 0).
    const skuRow = page
      .locator('.cxd-Transfer [class*="item"], .cxd-Transfer tr, .cxd-Transfer [class*="transfer"]', { hasText: 'SKU001' })
      .first();
    await skuRow.click({ timeout: 15_000 });
    await page.waitForTimeout(800);

    // ----- Step 4: Submit the order -----
    await page.locator('button:has-text("生成出库单")').click();
    await page.waitForTimeout(3000);

    // ----- Step 5: Verify an outbound order was created via API -----
    // customerOrderNo is auto-generated by the wizard (uuid), so assert by
    // querying the outbound plan order list. A fresh order leaves NEW then
    // advances to ASSIGNED (pre-allocation) within a few seconds, so assert the
    // list is non-empty and has at least one non-terminal order.
    const resp = await api.search(
      'WOutboundPlanOrder',
      {},
      [
        { name: 'customerOrderNo' },
        { name: 'orderNo' },
        { name: 'outboundPlanOrderStatus' },
        { name: 'totalQty' },
      ]
    );
    expect(resp.ok()).toBeTruthy();
    const data = await resp.json();
    const orders = data?.items || [];
    const hasActiveOrder = orders.some(
      (o) => !['CANCELED', 'CLOSED'].includes(o.outboundPlanOrderStatus)
    );
    console.log(`[verify] Outbound orders found: ${orders.length}, has active order: ${hasActiveOrder}`);
    expect(hasActiveOrder).toBeTruthy();
  });
});
