export enum CustomActionType {
    /** 上架选择容器格口事件 */
    CHOOSE_CONTAINER_SLOT_CODE = "CHOOSE_CONTAINER_SLOT_CODE",
    /** 点击异常登记按钮 */
    INBOUND_ABNORMAL_TIP = "INBOUND_ABNORMAL_TIP",
    /** 异常登记确认 */
    INBOUND_ABNORMAL_CONFIRM = "INBOUND_ABNORMAL_CONFIRM",
    /** 一码多品选择SKU确认 */
    INBOUND_SCAN_BARCODE_2_MANY_SKU_CODE = "INBOUND_SCAN_BARCODE_2_MANY_SKU_CODE",
}
